import enum


class FigureMatcher(enum.Enum):
    SCHEMATICS = 1
    FRACTURE_SEARCH = 2
    STRAIN_FRACTURE = 3
    SIMPLE_EXAMPLE = 4
    QUAD_REGIONS = 5
    QUAD_REGIONS_DISP = 6
    JOINT_DENSITY = 7
    ENS_AMPLITUDE = 8
    ENS_DIMENSIONLESS = 9
